---
title: "Project 2: projectpackage Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{projectpackage Tutorial}

  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
projectpackage is an R package for cross validation classification, t- test and testing hypotheses.

```{r setup}

#instructions for how to install your package from Github
penguins_rda <- load("../data/my_penguins.rda")
gapminder_rda<- load("../data/my_gapminder.rda")
write.csv(get(penguins_rda),"../data/my_penguins.csv")
write.csv(get(gapminder_rda),"../data/my_gapminder.csv")
my_penguins <- read.csv("../data/my_penguins.csv")


source("../code/my_rf_cv.R")
#source("/Users/harper/Documents/Fall2020/Stat302/Project2/project2pipieline/code/my_rf_cv.R")

#saveRDS()

```


```{r}
#A tutorial for my_rf_cv

library(randomForest)
library(dplyr)
library(tidyr)

my_table_1 <- data.frame()
body_mass_g <- na.omit(my_penguins$body_mass_g)
bill_length_mm <- na.omit(my_penguins$bill_length_mm)
bill_depth_mm <- na.omit(my_penguins$bill_depth_mm)
flipper_length_mm <- na.omit(my_penguins$flipper_length_mm)
        
for(i in 1:30) {
  result <- my_rf_cv(k = 2)
  my_table_1[i,1] <- unlist(result)
  #where error is 
  my_table_1[i,2] <- unlist(result) / nrow(my_penguins)
}

colnames(my_table_1) <- c("MSE", "cv_err")
rownames(my_table_1) <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30")

my_table_2 <- data.frame()
for(i in 1:30) {
  result <- my_rf_cv(k = 5)
  my_table_2[i,1] <- unlist(result)
  my_table_2[i,2] <- unlist(result) / nrow(my_penguins)
}
colnames(my_table_2) <- c("MSE", "cv_err")
rownames(my_table_2) <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30")

my_table_3 <- data.frame()
for(i in 1:30) {
  result <- my_rf_cv(k = 10)
  my_table_3[i,1] <- unlist(result)
  my_table_3[i,2] <- unlist(result) / nrow(my_penguins)
}
colnames(my_table_3) <- c("MSE", "cv_err")
rownames(my_table_3) <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30")


```

```{r}
library(ggplot2)
library(readr)
folds <- rep(c(2, 5, 10), each = 30) %>% as.factor() %>% is.vector()
all_table <- rbind(my_table_1, my_table_2, my_table_3)
df <- data.frame(all_table, folds)
ggplot(data = df,
       aes(
               x = unlist(folds),
               y = unlist(all_table),
               group = unlist(folds),
               fill = folds
       )) +
        geom_boxplot() +
        xlab("folds") +
        ylab("MSE") +
        labs("Misclassification Errors with different number of folds") +
        theme_bw() +
        theme(
                plot.title = element_text(hjust = 0.5, face = "bold"),
                axis.text.x = element_text(
                        angle = 45,
                        hjust = 1,
                        vjust = 1
                ),
                panel.spacing.x = unit(0.75, "cm")
        ) +
        scale_fill_brewer(
                type = "seq",
                palette = 1,
                direction = 1,
                aesthetics = "fill"
        )
 ggsave(path = "../Output/Figures", filename = "graph_1.jpg")
 
 
# simulation <- write_csv(c(my_table_1,my_table_2, my_table_3), file = "../Output/Result/simulation.csv")
```

```{r}
average_cverr_2 <- mean(as.numeric(my_table_1[2,]))
sd_cverr_2 <- sd(as.numeric(my_table_1[2,]))
average_cverr_5 <- mean(as.numeric(my_table_2[2,]))
sd_cverr_5 <- sd(as.numeric(my_table_2[2,]))
average_cverr_10 <- mean(as.numeric(my_table_3[2,]))
sd_cverr_10 <- sd(as.numeric(my_table_3[2,]))
row_1 <- cbind(average_cverr_2, sd_cverr_2)
row_2 <- cbind(average_cverr_5, sd_cverr_5)
row_3 <- cbind(average_cverr_10, sd_cverr_10)
cv_table <- rbind(row_1, row_2, row_3)
rownames(cv_table) <- c("k = 2", "k = 5", "k = 10")
colnames(cv_table) <- c("average", "sd")
cv_table
```
We can see from the table, the average and the standard deviation of ev_err become smaller as the value of k gets larger. This is because as the k gets larger, we test our model for more times, so that it becomes more accurate. Thus the values of cv_err get smaller.
